"""
Django settings for Ecomm project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
x=os.path.join(BASE_DIR,"Templates")
y=os.path.join(BASE_DIR,"Static")
MEDIA_DIR=os.path.join(BASE_DIR,"media")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3s!ayutab$=&2rd25#mf^bx9ecdqqk$vlf&^u=8c26xqz0x-__"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "myapp",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Ecomm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [x],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Ecomm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS=[y]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
MEDIA_ROOT=MEDIA_DIR
MEDIA_URL='/media/'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ecommence102@gmail.com'
EMAIL_HOST_PASSWORD = 'sevw dmjy ccle imia'



JAZZMIN_SETTINGS = {
    # It will add the title of the tab.
    "site_title": "Ecomm Admin",
    
    "site_header": "Library",
    # It will change the title on the Top of the Sidebar
    "site_brand": "Ecomm",
    # To change the logo at the top
     "site_logo": "../Icon.png",
     #Login form style 
    "login_logo": None,
    "login_logo_dark": None,
    #To give the logo the shape of the circle
     "site_logo_classes": "img-circle",
# Site Icon and welcome sign
    "site_icon": None,
    "welcome_sign": "Welcome to the library",
    # Copyright footer
        "copyright": "Acme Library Ltd",
        # To add a search bar from which the user can search
     "search_model": ["auth.User", "auth.Group"],
    # 
      "user_avatar": None,


 # Top Menu 

  "topmenu_links":[

        # Url that gets reversed (Permissions can be added) A Navbar kind of thingey
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

          {"model": "auth.User"},

          {"app": "Ecomm"},         
                  ],
  # User Menu
      "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

 # Side Menu 
  "show_sidebar": True,
    "navigation_expanded": True,
       # Related Modal #
         "related_modal_active": False,

  # UI Tweaks #
   "custom_css": None,
    "custom_js": None,
      "use_google_fonts_cdn": True,
       "show_ui_builder": True,
       








       }
