# Generated by Django 5.1 on 2024-09-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("confirmPassword", models.CharField(max_length=30)),
            ],
        ),
    ]
