# Generated by Django 5.1 on 2024-09-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_reg"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("Category", models.CharField(max_length=30)),
                ("Price", models.CharField(max_length=8)),
                ("Company", models.CharField(max_length=30)),
            ],
        ),
    ]
