# Generated by Django 5.1 on 2024-09-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Propage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("Image", models.ImageField(blank=True, upload_to="data")),
                ("Quantity", models.CharField(max_length=10)),
                ("Price", models.CharField(max_length=12)),
                ("Category", models.CharField(max_length=30)),
                ("description", models.TextField()),
            ],
        ),
    ]
