# Generated by Django 5.1 on 2024-09-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="reg",
            name="userAge",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
