# Generated by Django 5.1 on 2024-09-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_reg_userage"),
    ]

    operations = [
        migrations.AddField(
            model_name="reg",
            name="userAddress",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
