# Generated by Django 5.1 on 2024-09-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_reg_useraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="reg",
            name="UserBio",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
