# Generated by Django 5.1 on 2024-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_reg_userbio"),
    ]

    operations = [
        migrations.AddField(
            model_name="reg",
            name="UserProfile",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
