# Generated by Django 5.1 on 2024-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_reg_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="reg",
            name="UserImage",
            field=models.ImageField(
                blank=True, max_length=1000, null=True, upload_to=""
            ),
        ),
    ]
