# Generated by Django 5.1 on 2024-10-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_reg_userimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reg",
            name="UserProfile",
        ),
    ]
