# Generated by Django 5.1 on 2024-10-08 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Product_name", models.CharField(max_length=100)),
                ("Product_price", models.CharField(max_length=15)),
                ("Product_quantity", models.CharField(max_length=10)),
                ("Product_image", models.ImageField(max_length=1000, upload_to="")),
                ("Product_description", models.TextField()),
                (
                    "Category_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.category"
                    ),
                ),
            ],
        ),
    ]
